version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server
    environment:
      - BASE_URL=http://localhost:3000
      - LETSENCRYPT_EMAIL=kian.peymani@gmail.com
      - LETSENCRYPT_HOST=habitica.kianenigma.nl,www.habitica.kianenigma.nl
      - VIRTUAL_HOST=habitica.kianenigma.nl,www.habitica.kianenigma.nl
      - VIRTUAL_PORT=3000
    image: habitica
    networks:
      - habitica
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/habitica
      - /usr/src/habitica/node_modules
      - /usr/src/habitica/website/client/node_modules
  server:
    build:
      context: .
      dockerfile: ./Dockerfile-Dev
    command: ["npm", "start"]
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    image: habitica
    networks:
      - habitica
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/habitica
      - /usr/src/habitica/node_modules
  mongo:
    image: mongo:3.6
    networks:
      - habitica
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/data/db
networks:
  habitica:
    driver: bridge
